name: recipe_cook_book
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture
  stacked: ^1.5.7+1
  
  # Services
  stacked_services: ^0.3.4
  get_it: ^4.0.2
  injectable:

  # Navigation
  auto_route:

  # add flutter_screenutil
  flutter_screenutil: ^1.1.0

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator:
  injectable_generator:

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/font/Lato/Lato-Black.ttf
        - asset: assets/font/Lato/Lato-BlackItalic.ttf
        - asset: assets/font/Lato/Lato-Bold.ttf
        - asset: assets/font/Lato/Lato-BoldItalic.ttf
        - asset: assets/font/Lato/Lato-Italic.ttf
        - asset: assets/font/Lato/Lato-Light.ttf
        - asset: assets/font/Lato/Lato-LightItalic.ttf
        - asset: assets/font/Lato/Lato-Regular.ttf
        - asset: assets/font/Lato/Lato-Thin.ttf
        - asset: assets/font/Lato/Lato-ThinItalic.ttf
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto/Roboto-Black.ttf
        - asset: assets/font/Roboto/Roboto-BlackItalic.ttf
        - asset: assets/font/Roboto/Roboto-Bold.ttf
        - asset: assets/font/Roboto/Roboto-BoldItalic.ttf
        - asset: assets/font/Roboto/Roboto-Italic.ttf
        - asset: assets/font/Roboto/Roboto-Light.ttf
        - asset: assets/font/Roboto/Roboto-LightItalic.ttf
        - asset: assets/font/Roboto/Roboto-Medium.ttf
        - asset: assets/font/Roboto/Roboto-MediumItalic.ttf
        - asset: assets/font/Roboto/Roboto-Regular.ttf
        - asset: assets/font/Roboto/Roboto-Thin.ttf
        - asset: assets/font/Roboto/Roboto-ThinItalic.ttf